matrix:
  include:
#  - os: linux
#    python: 2.7
#    env: PYTHON_VERSION=2.7
#  - os: linux
#    python: 3.4
#    env: PYTHON_VERSION=3.4
#  - os: linux
#    python: 3.5
#    env: PYTHON_VERSION=3.5
  - os: linux
    python: 3.6
    env: PYTHON_VERSION=3.6
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=2.7
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=3.4
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=3.5
#  - os: osx
#    language: generic
#    env:
#    - PYTHON_VERSION=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == 2.* ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == 3.* ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == 2.* ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == 3.* ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda create -y -q -n py_entitymatching python=$PYTHON_VERSION nose           
  - source activate py_entitymatching
  - conda install -y -c conda-forge pyqt==4.11.4
  - conda install -y -c uwmagellan py_entitymatching

script:
  - source activate py_entitymatching                                         
  - python --version                                                            
  - nosetests py_entitymatching -m test_                                            

# timestamp: 2017.03.04-13.37.16
